export default {
  height:'auto',
  calcHeight: 30,
  tip: false,
  searchShow: true,
  searchMenuSpan: 4,
  border: true,
  index: false,
  viewBtn: true,
  selection: true,
  dialogClickModal: false,
  labelWidth: 140,
  searchLabelWidth: 70,
  searchSpan: 4,
  searchMenuPosition: 'left',
  column: [
    {
      label: "ID",
      prop: "id",
      type: "input",
      align: "center",
      overHidden: true,
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "车牌号",
      prop: "truckNumber",
      type: "input",
      align: "center",
      overHidden: true,
      search: true,
    },
    // {
    //   label: "磅房号",
    //   prop: "weightHouseId",
    //   type: "select",
    //   align: "center",
    //   overHidden: true,
    //   dicUrl: "/api/blade-system/dict-biz/dictionary?code=biz_sql_WEIGHT_HOUSE",
    //   props: {
    //     label: "dictValue",
    //     value: "dictKey"
    //   },
    //   search: true,
    // },

    {
      label: "通道号",
      prop: "channelName2",
      type: "input",
      align: "center",
      addDisplay: false,
      editDisplay: false,
      overHidden: true,
    },
    {
      label: "通道名称",
      prop: "channelName",
      type: "select",
      align: "center",
      overHidden: true,
      dicUrl: "/api/blade-system/dict-biz/dictionary?code=biz_CHANNEL",
      props: {
        label: "dictValue",
        value: "dictKey"
      },
    },
    {
      label: "箱号",
      prop: "cntrNo",
      type: "input",
      align: "center",
      overHidden: true,
    },
    {
      label: "箱ISO",
      prop: "sztp",
      type: "input",
      align: "center",
      overHidden: true,
    },
    // {
    //   label: "箱型",
    //   prop: "sztp2",
    //   type: "input",
    //   align: "center",
    //   overHidden: true,
    // },
    {
      label: "来源计划号",
      prop: "planNumber",
      type: "select",
      align: "center",
      overHidden: true,
      dicUrl: "/api/blade-system/dict-biz/dictionary?code=biz_sql_PLAN_NUMBER_LIST",
      props: {
        label: "dictValue",
        value: "dictKey"
      },
    },
    {
      label: "来源作业号",
      prop: "taskNumber",
      type: "input",
      align: "center",
      overHidden: true,
    },
    {
      label: "过磅类型",
      prop: "weightType",
      type: "select",
      align: "center",
      overHidden: true,
      dicUrl: "/api/blade-system/dict-biz/dictionary?code=biz_FE",
      props: {
        label: "dictValue",
        value: "dictKey"
      },
    },
    {
      label: "过磅称重",
      prop: "weight",
      type: "input",
      align: "center",
      overHidden: true,
    },
    {
      label: "过磅时间",
      prop: "weightTime",
      type: "input",
      align: "center",
      overHidden: true,
    },
    {
      label: "司磅员",
      prop: "weightUser",
      type: "select",
      align: "center",
      overHidden: true,
      dicUrl: "/api/blade-system/dict-biz/dictionary?code=biz_sql_USERNAME",
      props: {
        label: "dictValue",
        value: "dictKey"
      },
    },
    {
      label: "放行状态",
      prop: "action",
      type: "select",
      align: "center",
      overHidden: true,
      dicUrl: "/api/blade-system/dict-biz/dictionary?code=biz_GATE_ACTION",
      props: {
        label: "dictValue",
        value: "dictKey"
      },
    },
    {
      label: "放行信息",
      prop: "remark",
      type: "input",
      align: "center",
      overHidden: true,
      hide: true,
    },
    // {
    //   label: "创建人",
    //   prop: "createUserName",
    //   type: "input",
    //   align: "center",
    //   overHidden: true,
    //   addDisplay: false,
    //   editDisplay: false,
    //   viewDisplay: false,
    // },
    {
      label: "创建时间",
      prop: "createTime",
      type: "input",
      align: "center",
      overHidden: true,
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
    },
    // {
    //   label: "修改人",
    //   prop: "updateUserName",
    //   type: "input",
    //   align: "center",
    //   overHidden: true,
    //   addDisplay: false,
    //   editDisplay: false,
    //   viewDisplay: false,
    // },
    {
      label: "修改时间",
      prop: "updateTime",
      type: "input",
      align: "center",
      overHidden: true,
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
    },
  ]
}
