export default {
  height:'auto',
  calcHeight: 30,
  tip: false,
  searchShow: true,
  searchMenuSpan: 6,
  border: true,
  index: false,
  viewBtn: true,
  selection: true,
  dialogClickModal: false,
  labelWidth: 140,
  searchLabelWidth: 140,
  searchMenuPosition: 'left',
  column: [
    {
      label: "ID",
      prop: "id",
      type: "input",
      align: "center",
      overHidden: true,
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "计划单号",
      prop: "planNumber",
      type: "select",
      align: "center",
      overHidden: true,
      dicUrl: "/api/blade-system/dict-biz/dictionary?code=biz_sql_PLAN_NUMBER_LIST",
      props: {
        label: "dictValue",
        value: "dictKey"
      },
      search: true,
    },
    {
      label: "作业单号",
      prop: "taskNumber",
      type: "input",
      align: "center",
      overHidden: true,
    },
    {
      label: "物流公司",
      prop: "logisticsPtnr",
      type: "select",
      align: "center",
      overHidden: true,
      dicUrl: "/api/blade-system/dict-biz/dictionary?code=biz_sql_COM_LOGISTICS",
      props: {
        label: "dictValue",
        value: "dictKey"
      },
    },
    {
      label: "委托单位",
      prop: "ownerPtnr",
      type: "select",
      align: "center",
      overHidden: true,
      dicUrl: "/api/blade-system/dict-biz/dictionary?code=biz_sql_COM_OWNER",
      props: {
        label: "dictValue",
        value: "dictKey"
      },
      search: true,
    },
    {
      label: "货物名称",
      prop: "cargo",
      type: "select",
      align: "center",
      overHidden: true,
      dicUrl: "/api/blade-system/dict-biz/dictionary?code=biz_sql_CARGO_NAMES",
      props: {
        label: "dictValue",
        value: "dictKey"
      },
    },
    {
      label: "作业车牌",
      prop: "truckNumber",
      type: "input",
      align: "center",
      overHidden: true,
      search: true,
    },
    {
      label: "作业箱号",
      prop: "cntrNo",
      type: "input",
      align: "center",
      overHidden: true,
    },
    {
      label: "作业箱ISO",
      prop: "cntrIso",
      type: "input",
      align: "center",
      overHidden: true,
    },
    {
      label: "空车状态",
      prop: "emptyStatus",
      type: "select",
      align: "center",
      overHidden: true,
      dicUrl: "/api/blade-system/dict-biz/dictionary?code=biz_WEIGHT_EMPTY_STATUS",
      props: {
        label: "dictValue",
        value: "dictKey"
      },
    },
    {
      label: "空车时间",
      prop: "emptyTime",
      type: "input",
      align: "center",
      overHidden: true,
    },
    {
      label: "空车重量",
      prop: "emptyWgt",
      type: "input",
      align: "center",
      overHidden: true,
    },
    {
      label: "空车司磅员",
      prop: "emptyWeighman",
      type: "input",
      align: "center",
      overHidden: true,
    },
    {
      label: "出库状态",
      prop: "outboundStatus",
      type: "select",
      align: "center",
      overHidden: true,
      dicUrl: "/api/blade-system/dict-biz/dictionary?code=biz_OUT_STORE_STATUS",
      props: {
        label: "dictValue",
        value: "dictKey"
      },
    },
    {
      label: "出库地点",
      prop: "outboundYard",
      type: "select",
      align: "center",
      overHidden: true,
      dicUrl: "/api/blade-system/dict-biz/dictionary?code=biz_sql_BULK_YARD",
      props: {
        label: "dictValue",
        value: "dictKey"
      },
    },
    {
      label: "重车状态",
      prop: "fullStatus",
      type: "select",
      align: "center",
      overHidden: true,
      dicUrl: "/api/blade-system/dict-biz/dictionary?code=biz_WEIGHT_STATUS",
      props: {
        label: "dictValue",
        value: "dictKey"
      },
    },
    {
      label: "重车时间",
      prop: "fullTime",
      type: "input",
      align: "center",
      overHidden: true,
    },
    {
      label: "重车重量",
      prop: "fullWgt",
      type: "input",
      align: "center",
      overHidden: true,
    },
    {
      label: "重车司磅员",
      prop: "fullWeighman",
      type: "input",
      align: "center",
      overHidden: true,
    },
    {
      label: "灌箱状态",
      prop: "loadingStatus",
      type: "select",
      align: "center",
      overHidden: true,
      dicUrl: "/api/blade-system/dict-biz/dictionary?code=biz_FILL_STATUS",
      props: {
        label: "dictValue",
        value: "dictKey"
      },
    },
    {
      label: "灌箱时间",
      prop: "loadingTime",
      type: "date",
      align: "center",
      overHidden: true,
      format: "yyyy-MM-dd HH:mm:ss",
      valueFormat: "yyyy-MM-dd HH:mm:ss",
    },
    {
      label: "灌箱人",
      prop: "loadingUser",
      type: "input",
      align: "center",
      overHidden: true,
    },
    {
      label: "拆箱状态",
      prop: "unloadingStatus",
      type: "select",
      align: "center",
      overHidden: true,
      dicUrl: "/api/blade-system/dict-biz/dictionary?code=biz_UNBOX_STATUS",
      props: {
        label: "dictValue",
        value: "dictKey"
      },
    },
    {
      label: "拆箱时间",
      prop: "unloadingTime",
      type: "date",
      align: "center",
      overHidden: true,
      format: "yyyy-MM-dd HH:mm:ss",
      valueFormat: "yyyy-MM-dd HH:mm:ss",
    },
    {
      label: "拆箱人",
      prop: "unloadingUser",
      type: "input",
      align: "center",
      overHidden: true,
    },
    {
      label: "封条号",
      prop: "sealNumber",
      type: "input",
      align: "center",
      overHidden: true,
    },
    {
      label: "作业状态",
      prop: "taskStatus",
      type: "select",
      align: "center",
      overHidden: true,
      dicUrl: "/api/blade-system/dict-biz/dictionary?code=biz_TASK_STATUS",
      props: {
        label: "dictValue",
        value: "dictKey"
      },
      search: true,
    },
    {
      label: "进闸状态",
      prop: "gateInStatus",
      type: "select",
      align: "center",
      overHidden: true,
      dicUrl: "/api/blade-system/dict-biz/dictionary?code=biz_GATE_IN_STATUS",
      props: {
        label: "dictValue",
        value: "dictKey"
      },
    },
    {
      label: "进闸时间",
      prop: "gateInTime",
      type: "date",
      align: "center",
      overHidden: true,
      format: "yyyy-MM-dd HH:mm:ss",
      valueFormat: "yyyy-MM-dd HH:mm:ss",
    },
    {
      label: "出闸状态",
      prop: "gateOutStatus",
      type: "select",
      align: "center",
      overHidden: true,
      dicUrl: "/api/blade-system/dict-biz/dictionary?code=biz_GATE_OUT_STATUS",
      props: {
        label: "dictValue",
        value: "dictKey"
      },
    },
    {
      label: "出闸时间",
      prop: "gateOutTime",
      type: "date",
      align: "center",
      overHidden: true,
      format: "yyyy-MM-dd HH:mm:ss",
      valueFormat: "yyyy-MM-dd HH:mm:ss",
    },
    {
      label: "提还类型",
      prop: "ioMode",
      type: "select",
      align: "center",
      overHidden: true,
      dicUrl: "/api/blade-system/dict-biz/dictionary?code=biz_IO_MODE",
      props: {
        label: "dictValue",
        value: "dictKey"
      },
    },
    {
      label: "排序",
      prop: "orderIndex",
      type: "input",
      align: "center",
      overHidden: true,
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "创建人",
      prop: "createUser",
      type: "input",
      align: "center",
      overHidden: true,
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
    },
    {
      label: "创建部门",
      prop: "createDept",
      type: "input",
      align: "center",
      overHidden: true,
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "创建时间",
      prop: "createTime",
      type: "input",
      align: "center",
      overHidden: true,
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
    },
    {
      label: "修改人",
      prop: "updateUser",
      type: "input",
      align: "center",
      overHidden: true,
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
    },
    {
      label: "修改时间",
      prop: "updateTime",
      type: "input",
      align: "center",
      overHidden: true,
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
    },
    {
      label: "状态",
      prop: "status",
      type: "input",
      align: "center",
      overHidden: true,
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "是否已删除",
      prop: "isDeleted",
      type: "input",
      align: "center",
      overHidden: true,
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
  ]
}
