export default {
  height:'auto',
  calcHeight: 30,
  tip: false,
  searchShow: true,
  searchMenuSpan: 3,
  border: true,
  index: false,
  viewBtn: true,
  selection: true,
  dialogClickModal: false,
  labelWidth: 140,
  searchLabelWidth: 100,
  searchSpan:3,
  searchMenuPosition: 'left',
  column: [
    {
      label: "ID",
      prop: "id",
      type: "input",
      align: "center",
      overHidden: true,
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "箱号",
      prop: "cntrNo",
      type: "input",
      align: "center",
      overHidden: true,
    },
    {
      label: "出入类型",
      prop: "ioMode",
      type: "select",
      align: "center",
      overHidden: true,
      dicUrl: "/api/blade-system/dict-biz/dictionary?code=biz_IO_MODE",
      props: {
        label: "dictValue",
        value: "dictKey"
      },
      search: true,
    },
    {
      label: "空重",
      prop: "fe",
      type: "select",
      align: "center",
      overHidden: true,
      dicUrl: "/api/blade-system/dict-biz/dictionary?code=biz_FE",
      props: {
        label: "dictValue",
        value: "dictKey"
      },
    },
    {
      label: "箱型ISO",
      prop: "sztp",
      type: "input",
      align: "center",
      overHidden: true,
    },
    // {
    //   label: "箱型",
    //   prop: "sztp2",
    //   type: "input",
    //   align: "center",
    //   overHidden: true,
    // },
    {
      label: "货名",
      prop: "cargoType",
      type: "select",
      align: "center",
      overHidden: true,
      dicUrl: "/api/blade-system/dict-biz/dictionary?code=biz_sql_CARGO_NAMES",
      props: {
        label: "dictValue",
        value: "dictKey"
      },
    },
    {
      label: "净重",
      prop: "wgt",
      type: "input",
      align: "center",
      overHidden: true,
    },
    {
      label: "空箱堆场",
      prop: "yardId2",
      type: "select",
      align: "center",
      overHidden: true,
      dicUrl: "/api/blade-system/dict-biz/dictionary?code=biz_sql_CNTR_YARD",
      props: {
        label: "dictValue",
        value: "dictKey"
      },
      search: true,
      searchLabelWidth: 100,
    },
    {
      label: "重箱堆场",
      prop: "yardId",
      type: "select",
      align: "center",
      overHidden: true,
      dicUrl: "/api/blade-system/dict-biz/dictionary?code=biz_sql_CNTR_YARD",
      props: {
        label: "dictValue",
        value: "dictKey"
      },
      search: true,
      searchLabelWidth: 100,
    },
    {
      label: "委托单位",
      prop: "owner",
      type: "select",
      align: "center",
      overHidden: true,
      dicUrl: "/api/blade-system/dict-biz/dictionary?code=biz_sql_COM_OWNER",
      props: {
        label: "dictValue",
        value: "dictKey"
      },
      search: true,
      searchLabelWidth: 100,
    },
    {
      label: "物流公司",
      prop: "logisticsCompany",
      type: "select",
      align: "center",
      overHidden: true,
      dicUrl: "/api/blade-system/dict-biz/dictionary?code=biz_sql_COM_LOGISTICS",
      props: {
        label: "dictValue",
        value: "dictKey"
      },
    },
    {
      label: "作业车牌",
      prop: "truckNumber",
      type: "select",
      align: "center",
      overHidden: true,
      dicUrl: "/api/blade-system/dict-biz/dictionary?code=biz_sql_TRUCK_LIST",
      props: {
        label: "dictValue",
        value: "dictKey"
      },
      search: true,
    },
    {
      width: 140,
      label: "来源计划号",
      prop: "planNumber",
      type: "select",
      align: "center",
      overHidden: true,
      dicUrl: "/api/blade-system/dict-biz/dictionary?code=biz_sql_PLAN_NUMBER_LIST",
      props: {
        label: "dictValue",
        value: "dictKey"
      },
    },
    {
      width: 140,
      label: "来源作业号",
      prop: "taskNumber",
      type: "input",
      align: "center",
      overHidden: true,
    },
    {
      label: "计划类型",
      prop: "planType",
      type: "select",
      align: "center",
      overHidden: true,
      dicUrl: "/api/blade-system/dict-biz/dictionary?code=biz_PLAN_TYPE",
      props: {
        label: "dictValue",
        value: "dictKey"
      },
    },
    // {
    //   label: "创建人",
    //   prop: "createUserName",
    //   type: "input",
    //   align: "center",
    //   overHidden: true,
    //   addDisplay: false,
    //   editDisplay: false,
    //   viewDisplay: false,
    // },
    {
      label: "封条号",
      prop: "sealNumber",
      type: "input",
      align: "center",
      overHidden: true,
    },
    {
      width: 140,
      label: "创建时间",
      prop: "createTime",
      type: "datetime",
      align: "center",
      overHidden: true,
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      search: true,
      searchRange:true,
      valueFormat:'yyyy-MM-dd HH:mm:ss'
    },
    // {
    //   label: "修改人",
    //   prop: "updateUserName",
    //   type: "input",
    //   align: "center",
    //   overHidden: true,
    //   addDisplay: false,
    //   editDisplay: false,
    //   viewDisplay: false,
    // },
    // {
    //   label: "修改时间",
    //   prop: "updateTime",
    //   type: "input",
    //   align: "center",
    //   overHidden: true,
    //   addDisplay: false,
    //   editDisplay: false,
    //   viewDisplay: false,
    // },
  ]
}
