export default {
  height:'auto',
  calcHeight: 30,
  tip: false,
  searchShow: false,
  searchMenuSpan: 6,
  border: true,
  index: false,
  viewBtn: true,
  selection: true,
  dialogClickModal: false,
  labelWidth: 140,
  searchLabelWidth: 100,
  searchMenuPosition: 'left',
  addBtn: false,
  delBtn: false,
  column: [
    {
      label: "ID",
      prop: "id",
      type: "input",
      align: "center",
      overHidden: true,
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true
    },
    {
      label: "计划",
      prop: "planNumber",
      type: "input",
      align: "center",
      overHidden: true,
      search: true,
    },
    {
      label: "作业号",
      prop: "taskNumber",
      type: "input",
      align: "center",
      overHidden: true,
      search: true,
    },
    {
      label: "车号",
      prop: "truckNumber",
      type: "input",
      align: "center",
      overHidden: true,
      search: true,
    },
    {
      label: "类型",
      prop: "type",
      type: "input",
      align: "center",
      overHidden: true,
      search: true,
    },
    // {
    //   label: "计划状态",
    //   prop: "planStatus",
    //   type: "input",
    //   align: "center",
    //   overHidden: true,
    // },
    {
      label: "任务状态",
      prop: "taskStatus",
      type: "input",
      align: "center",
      overHidden: true,
    },
    {
      label: "日志",
      prop: "content",
      type: "input",
      align: "center",
      overHidden: true,
    },
    // {
    //   label: "",
    //   prop: "p1",
    //   type: "input",
    //   align: "center",
    //   overHidden: true,
    //   addDisplay: false,
    //   editDisplay: false,
    //   viewDisplay: false,
    // },
    // {
    //   label: "",
    //   prop: "p2",
    //   type: "input",
    //   align: "center",
    //   overHidden: true,
    //   addDisplay: false,
    //   editDisplay: false,
    //   viewDisplay: false,
    // },
    // {
    //   label: "",
    //   prop: "p3",
    //   type: "input",
    //   align: "center",
    //   overHidden: true,
    //   addDisplay: false,
    //   editDisplay: false,
    //   viewDisplay: false,
    // },
    // {
    //   label: "排序",
    //   prop: "orderIndex",
    //   type: "input",
    //   align: "center",
    //   overHidden: true,
    //   addDisplay: false,
    //   editDisplay: false,
    //   viewDisplay: false,
    //   hide: true,
    // },
    // {
    //   label: "创建人",
    //   prop: "createUser",
    //   type: "input",
    //   align: "center",
    //   overHidden: true,
    //   addDisplay: false,
    //   editDisplay: false,
    //   viewDisplay: false,
    //   hide: true,
    // },
    // {
    //   label: "创建部门",
    //   prop: "createDept",
    //   type: "input",
    //   align: "center",
    //   overHidden: true,
    //   addDisplay: false,
    //   editDisplay: false,
    //   viewDisplay: false,
    //   hide: true,
    // },
    {
      label: "创建时间",
      prop: "createTime",
      type: "input",
      align: "center",
      overHidden: true,
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
    },
    // {
    //   label: "修改人",
    //   prop: "updateUser",
    //   type: "input",
    //   align: "center",
    //   overHidden: true,
    //   addDisplay: false,
    //   editDisplay: false,
    //   viewDisplay: false,
    //   hide: true,
    // },
    // {
    //   label: "修改时间",
    //   prop: "updateTime",
    //   type: "input",
    //   align: "center",
    //   overHidden: true,
    //   addDisplay: false,
    //   editDisplay: false,
    //   viewDisplay: false,
    //   hide: true,
    // },
    // {
    //   label: "状态",
    //   prop: "status",
    //   type: "input",
    //   align: "center",
    //   overHidden: true,
    //   addDisplay: false,
    //   editDisplay: false,
    //   viewDisplay: false,
    //   hide: true,
    // },
    // {
    //   label: "是否已删除",
    //   prop: "isDeleted",
    //   type: "input",
    //   align: "center",
    //   overHidden: true,
    //   addDisplay: false,
    //   editDisplay: false,
    //   viewDisplay: false,
    //   hide: true,
    // },
  ]
}
