export default {
  height:'auto',
  calcHeight: 30,
  tip: false,
  searchShow: true,
  searchSpan: 4,
  searchMenuSpan: 6,
  border: true,
  index: false,
  viewBtn: true,
  selection: true,
  dialogClickModal: false,
  labelWidth: 140,
  searchLabelWidth: 90,
  searchMenuPosition: 'left',
  column: [
    {
      label: "ID",
      prop: "id",
      type: "input",
      align: "center",
      overHidden: true,
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "作业类型",
      prop: "planType",
      type: "select",
      align: "center",
      overHidden: true,
      dicUrl: "/api/blade-system/dict-biz/dictionary?code=biz_PLAN_TYPE",
      props: {
        label: "dictValue",
        value: "dictKey"
      },
      search: true,
    },
    {
      label: "计划描述",
      prop: "planDescr",
      type: "input",
      align: "center",
      overHidden: true,
    },
    {
      label: "计划单号",
      prop: "planNumber",
      type: "input",
      align: "center",
      overHidden: true,
    },
    {
      label: "出库单号",
      prop: "coutFormId",
      type: "input",
      align: "center",
      overHidden: true,
    },
    {
      label: "服务单号",
      prop: "serviceOrder",
      type: "input",
      align: "center",
      overHidden: true,
    },
    {
      label: "BDB地磅号",
      prop: "bdb",
      type: "input",
      align: "center",
      overHidden: true,
    },
    {
      label: "物流公司",
      prop: "logisticsPtnr",
      type: "select",
      align: "center",
      overHidden: true,
      dicUrl: "/api/blade-system/dict-biz/dictionary?code=biz_sql_COM_LOGISTICS",
      props: {
        label: "dictValue",
        value: "dictKey"
      },
      search: true,
    },
    {
      label: "委托单位",
      prop: "ownerPtnr",
      type: "select",
      align: "center",
      overHidden: true,
      dicUrl: "/api/blade-system/dict-biz/dictionary?code=biz_sql_COM_OWNER",
      props: {
        label: "dictValue",
        value: "dictKey"
      },
      search: true,
    },
    {
      label: "货物名称",
      prop: "cargo",
      type: "select",
      align: "center",
      overHidden: true,
      dicUrl: "/api/blade-system/dict-biz/dictionary?code=biz_sql_CARGO_NAMES",
      props: {
        label: "dictValue",
        value: "dictKey"
      },
      search: true,
    },
    {
      label: "空箱堆场",
      prop: "emptyYard",
      type: "select",
      align: "center",
      overHidden: true,
      dicUrl: "/api/blade-system/dict-biz/dictionary?code=biz_sql_CNTR_YARD_E",
      props: {
        label: "dictValue",
        value: "dictKey"
      },
    },
    {
      label: "重箱堆场",
      prop: "fullYard",
      type: "select",
      align: "center",
      overHidden: true,
      dicUrl: "/api/blade-system/dict-biz/dictionary?code=biz_sql_CNTR_YARD_F",
      props: {
        label: "dictValue",
        value: "dictKey"
      },
    },
    {
      label: "散货堆场",
      prop: "bulkYard",
      type: "input",
      align: "center",
      overHidden: true,
    },
    {
      label: "终端流向",
      prop: "direction",
      type: "input",
      align: "center",
      overHidden: true,
    },
    {
      label: "作业计划量(吨)",
      prop: "wgt",
      type: "input",
      align: "center",
      overHidden: true,
    },
    {
      label: "过磅地点",
      prop: "wgtHouse",
      type: "input",
      align: "center",
      overHidden: true,
    },
    // {
    //   label: "循环计划",
    //   prop: "loop",
    //   type: "select",
    //   align: "center",
    //   overHidden: true,
    //   dicUrl: "/api/blade-system/dict-biz/dictionary?code=biz_YES_NO",
    //   props: {
    //     label: "dictValue",
    //     value: "dictKey"
    //   },
    // },
    {
      label: "作业有效期",
      prop: "expiryTime",
      type: "date",
      align: "center",
      overHidden: true,
      format: "yyyy-MM-dd HH:mm:ss",
      valueFormat: "yyyy-MM-dd HH:mm:ss",
    },
    {
      label: "完成量(吨)",
      prop: "completedWgt",
      type: "input",
      align: "center",
      overHidden: true,
    },
    {
      label: "完成车数",
      prop: "completedTimes",
      type: "input",
      align: "center",
      overHidden: true,
    },
    {
      label: "作业开始时间",
      prop: "taskStartTime",
      type: "input",
      align: "center",
      overHidden: true,
    },
    {
      label: "作业结束时间",
      prop: "taskEndTime",
      type: "input",
      align: "center",
      overHidden: true,
    },
    {
      label: "计划状态",
      prop: "planStatus",
      type: "select",
      align: "center",
      overHidden: true,
      dicUrl: "/api/blade-system/dict-biz/dictionary?code=biz_PLAN_STATUS",
      props: {
        label: "dictValue",
        value: "dictKey"
      },
    },
    {
      label: "排序",
      prop: "orderIndex",
      type: "input",
      align: "center",
      overHidden: true,
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "创建人",
      prop: "createUserName",
      type: "input",
      align: "center",
      overHidden: true,
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
    },
    {
      label: "创建部门",
      prop: "createDept",
      type: "input",
      align: "center",
      overHidden: true,
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "创建时间",
      prop: "createTime",
      type: "input",
      align: "center",
      overHidden: true,
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
    },
    {
      label: "修改人",
      prop: "updateUserName",
      type: "input",
      align: "center",
      overHidden: true,
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
    },
    {
      label: "修改时间",
      prop: "updateTime",
      type: "input",
      align: "center",
      overHidden: true,
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
    }
  ]
}
