export default {
  height:'auto',
  calcHeight: 30,
  tip: false,
  searchShow: true,
  searchMenuSpan: 4,
  border: true,
  index: false,
  viewBtn: true,
  selection: true,
  dialogClickModal: false,
  labelWidth: 140,
  searchSpan: 4,
  searchLabelWidth: 100,
  searchMenuPosition: 'left',
  column: [
    {
      label: "ID",
      prop: "id",
      type: "input",
      align: "center",
      overHidden: true,
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "车牌号",
      prop: "truckNumber",
      type: "input",
      align: "center",
      overHidden: true,
      search: true,
    },
    {
      label: "通道号",
      prop: "gateNumber2",
      type: "input",
      align: "center",
      addDisplay: false,
      editDisplay: false,
      overHidden: true,
    },
    {
      label: "通道名称",
      prop: "gateNumber",
      type: "select",
      align: "center",
      overHidden: true,
      dicUrl: "/api/blade-system/dict-biz/dictionary?code=biz_CHANNEL",
      props: {
        label: "dictValue",
        value: "dictKey"
      },
    },
    {
      label: "前箱号",
      prop: "cntrNoF",
      type: "input",
      align: "center",
      overHidden: true,
    },
    {
      label: "前箱ISO",
      prop: "sztp2F",
      type: "input",
      align: "center",
      overHidden: true,
    },
    {
      label: "前计划号",
      prop: "planNumberF",
      type: "input",
      align: "center",
      overHidden: true,
    },
    {
      label: "前作业号",
      prop: "taskNumberF",
      type: "input",
      align: "center",
      overHidden: true,
    },
    {
      label: "后箱号",
      prop: "cntrNoB",
      type: "input",
      align: "center",
      overHidden: true,
    },
    {
      label: "后箱ISO",
      prop: "sztp2B",
      type: "input",
      align: "center",
      overHidden: true,
    },
    {
      label: "后计划号",
      prop: "planNumberB",
      type: "input",
      align: "center",
      overHidden: true,
    },
    {
      label: "后作业号",
      prop: "taskNumberB",
      type: "input",
      align: "center",
      overHidden: true,
    },
    {
      label: "过闸类型",
      prop: "throughType",
      type: "select",
      align: "center",
      overHidden: true,
      dicUrl: "/api/blade-system/dict-biz/dictionary?code=biz_THROUGH_TYPE",
      props: {
        label: "dictValue",
        value: "dictKey"
      },
    },
    {
      label: "过闸时间",
      prop: "throughTime",
      type: "datetime",
      align: "center",
      overHidden: true,
      format: "yyyy-MM-dd HH:mm:ss",
      valueFormat: "yyyy-MM-dd HH:mm:ss",
    },
    {
      label: "闸口员",
      prop: "gateMan",
      type: "select",
      align: "center",
      overHidden: true,
      dicUrl: "/api/blade-system/dict-biz/dictionary?code=biz_sql_USERNAME",
      props: {
        label: "dictValue",
        value: "dictKey"
      },
    },
    {
      label: "放行状态",
      prop: "action",
      type: "select",
      align: "center",
      overHidden: true,
      dicUrl: "/api/blade-system/dict-biz/dictionary?code=biz_GATE_ACTION",
      props: {
        label: "dictValue",
        value: "dictKey"
      },
    },
    {
      label: "放行信息",
      prop: "actionLog",
      type: "input",
      align: "center",
      overHidden: true,
    },
    // {
    //   label: "创建人",
    //   prop: "createUserName",
    //   type: "input",
    //   align: "center",
    //   overHidden: true,
    //   addDisplay: false,
    //   editDisplay: false,
    //   viewDisplay: false,
    // },
    {
      label: "创建时间",
      prop: "createTime",
      type: "input",
      align: "center",
      overHidden: true,
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
    },
    // {
    //   label: "修改人",
    //   prop: "updateUserName",
    //   type: "input",
    //   align: "center",
    //   overHidden: true,
    //   addDisplay: false,
    //   editDisplay: false,
    //   viewDisplay: false,
    // },
    // {
    //   label: "修改时间",
    //   prop: "updateTime",
    //   type: "input",
    //   align: "center",
    //   overHidden: true,
    //   addDisplay: false,
    //   editDisplay: false,
    //   viewDisplay: false,
    // },

  ]
}
