export default {
  height:'auto',
  calcHeight: 30,
  tip: false,
  searchShow: true,
  border: true,
  index: false,
  viewBtn: true,
  selection: true,
  dialogClickModal: false,
  labelWidth: 140,
  searchLabelWidth: 100,
  searchMenuSpan: 5,
  searchSpan: 4,
  searchMenuPosition: 'left',
  menuWidth: 90,
  addBtn: false,
  editBtn: false,
  delBtn: false,
  column: [
    {
      span: 24,
      width: 100,
      label: "日志类型",
      prop: "type",
      type: "select",
      align: "center",
      overHidden: true,
      dicUrl: "/api/blade-system/dict-biz/dictionary?code=biz_SERVICE_API_TYPE",
      props: {
        label: "dictValue",
        value: "dictKey"
      },
      search: true,
    },
    // {
    //   label: "服务ID",
    //   prop: "serviceId",
    //   type: "input",
    //   align: "center",
    //   overHidden: true,
    // },
    // {
    //   label: "服务器名",
    //   prop: "serverHost",
    //   type: "input",
    //   align: "center",
    //   overHidden: true,
    // },
    // {
    //   label: "服务器IP地址",
    //   prop: "serverIp",
    //   type: "input",
    //   align: "center",
    //   overHidden: true,
    // },
    // {
    //   label: "服务器环境",
    //   prop: "env",
    //   type: "input",
    //   align: "center",
    //   overHidden: true,
    // },
    {
      width: 200,
      span: 24,
      label: "日志标题",
      prop: "title",
      type: "input",
      align: "center",
      overHidden: true,
      search: true,
    },
    {
      width: 100,
      label: "操作方式",
      prop: "method",
      type: "input",
      align: "center",
      overHidden: true,
      span: 24,
    },
    {
      label: "请求URI",
      prop: "requestUri",
      type: "input",
      align: "left",
      overHidden: true,
      search: true,
      span: 24,
    },
    {
      label: "用户代理",
      prop: "userAgent",
      type: "input",
      align: "center",
      overHidden: true,
      hide: true,
      span: 24,
    },
    {
      label: "请求头信息",
      prop: "requestHeader",
      type: "input",
      align: "center",
      overHidden: true,
      hide: true,
      span: 24,
    },
    // {
    //   label: "返回头信息",
    //   prop: "responseHeader",
    //   type: "textarea",
    //   align: "center",
    //   overHidden: true,
    //   hide: true,
    //   span: 24,
    // },
    // {
    //   width: 100,
    //   label: "返回代码",
    //   prop: "responseStatus",
    //   type: "input",
    //   align: "center",
    //   overHidden: true,
    //   span: 24,
    // },
    // {
    //   label: "方法类",
    //   prop: "methodClass",
    //   type: "input",
    //   align: "center",
    //   overHidden: true,
    // },
    // {
    //   label: "方法名",
    //   prop: "methodName",
    //   type: "input",
    //   align: "center",
    //   overHidden: true,
    // },
    {
      label: "参数数据",
      prop: "params",
      type: "textarea",
      align: "center",
      overHidden: true,
      hide: true,
      span: 24,
    },
    
    {
      label: "返回数据",
      prop: "response",
      type: "textarea",
      align: "left",
      overHidden: true,
      span: 24,
    },
    {
      label: "IP地址",
      prop: "remoteIp",
      type: "input",
      align: "center",
      overHidden: true,
      hide: true,
      span: 24,
    },
    {
      width: 150,
      label: "时间",
      prop: "createTime",
      type: "input",
      align: "center",
      overHidden: true,
      addDisplay: false,
      editDisplay: false,
    },
  ]
}
