export default {
  height:'auto',
  calcHeight: 30,
  tip: false,
  searchShow: true,
  searchMenuSpan: 6,
  border: true,
  index: false,
  viewBtn: true,
  selection: true,
  dialogClickModal: false,
  labelWidth: 140,
  searchLabelWidth: 140,
  searchMenuPosition: 'left',
  column: [
    {
      label: "ID",
      prop: "id",
      type: "input",
      align: "center",
      overHidden: true,
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "在场箱ID",
      prop: "inventoryId",
      type: "input",
      align: "center",
      overHidden: true,
    },
    {
      label: "还箱在场箱ID",
      prop: "inventory2Id",
      type: "input",
      align: "center",
      overHidden: true,
    },
    {
      label: "委托单位",
      prop: "owner",
      type: "select",
      align: "center",
      overHidden: true,
      dicUrl: "/api/blade-system/dict-biz/dictionary?code=biz_sql_COM_OWNER",
      props: {
        label: "dictValue",
        value: "dictKey"
      },
      search: true,
    },
    {
      label: "集装箱编号",
      prop: "cntrNo",
      type: "input",
      align: "center",
      overHidden: true,
    },
    {
      label: "物流公司",
      prop: "logisticsCompany",
      type: "select",
      align: "center",
      overHidden: true,
      dicUrl: "/api/blade-system/dict-biz/dictionary?code=biz_sql_COM_LOGISTICS",
      props: {
        label: "dictValue",
        value: "dictKey"
      },
    },
    {
      label: "空重",
      prop: "fe",
      type: "select",
      align: "center",
      overHidden: true,
      dicUrl: "/api/blade-system/dict-biz/dictionary?code=biz_FE",
      props: {
        label: "dictValue",
        value: "dictKey"
      },
    },
    {
      label: "箱型尺寸",
      prop: "sztp",
      type: "input",
      align: "center",
      overHidden: true,
    },
    {
      label: "箱ISO",
      prop: "sztp2",
      type: "input",
      align: "center",
      overHidden: true,
    },
    {
      label: "残损情况",
      prop: "dmgStatus",
      type: "select",
      align: "center",
      overHidden: true,
      dicUrl: "/api/blade-system/dict-biz/dictionary?code=biz_DMG_STATUS",
      props: {
        label: "dictValue",
        value: "dictKey"
      },
    },
    {
      label: "货名",
      prop: "cargoType",
      type: "select",
      align: "center",
      overHidden: true,
      dicUrl: "/api/blade-system/dict-biz/dictionary?code=biz_CARGO_TYPE",
      props: {
        label: "dictValue",
        value: "dictKey"
      },
    },
    {
      label: "净重",
      prop: "wgt",
      type: "input",
      align: "center",
      overHidden: true,
    },
    {
      label: "堆场",
      prop: "yardId",
      type: "input",
      align: "center",
      overHidden: true,
    },
    {
      label: "船舶代码",
      prop: "vslCd",
      type: "input",
      align: "center",
      overHidden: true,
    },
    {
      label: "航次",
      prop: "voy",
      type: "input",
      align: "center",
      overHidden: true,
    },
    {
      label: "作业箱任务状态",
      prop: "taskStatus",
      type: "select",
      align: "center",
      overHidden: true,
      dicUrl: "/api/blade-system/dict-biz/dictionary?code=biz_TASK_STATUS",
      props: {
        label: "dictValue",
        value: "dictKey"
      },
    },
    {
      label: "分配计划号",
      prop: "assignPlanNumber",
      type: "input",
      align: "center",
      overHidden: true,
    },
    {
      label: "创建人",
      prop: "createUser",
      type: "input",
      align: "center",
      overHidden: true,
      hide: true,
    },
    {
      label: "创建部门",
      prop: "createDept",
      type: "input",
      align: "center",
      overHidden: true,
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "创建时间",
      prop: "createTime",
      type: "input",
      align: "center",
      overHidden: true,
      hide: true,
    },
    {
      label: "修改人",
      prop: "updateUser",
      type: "input",
      align: "center",
      overHidden: true,
      hide: true,
    },
    {
      label: "修改时间",
      prop: "updateTime",
      type: "input",
      align: "center",
      overHidden: true,
      hide: true,
    },
    {
      label: "状态",
      prop: "status",
      type: "input",
      align: "center",
      overHidden: true,
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "是否已删除",
      prop: "isDeleted",
      type: "input",
      align: "center",
      overHidden: true,
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
  ]
}
